# Generated by Django 5.1.5 on 2025-01-22 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patients_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('reports', models.BinaryField(blank=True, null=True)),
                ('relative_contact', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
        ),
    ]
