# Generated by Django 5.1.5 on 2025-01-22 01:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('degree', models.CharField(default='Not Specified', max_length=50)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('years_of_experience', models.IntegerField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile_description', models.TextField(default='Not Specified')),
                ('max_patients_per_day', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.specialization')),
            ],
        ),
    ]
