# Generated by Django 5.1.5 on 2025-01-21 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('years_of_experience', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile_description', models.TextField(blank=True, null=True)),
                ('max_patients_per_day', models.IntegerField(default=10)),
                ('availability_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('unavailable', 'Unavailable')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
