# Generated by Django 5.1.5 on 2025-01-22 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorleave_weeklyschedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyschedule',
            unique_together={('doctor', 'date')},
        ),
    ]
