# Generated by Django 5.1.5 on 2025-01-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_specialization_category_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='category',
        ),
        migrations.AddField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_description',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
