# Generated by Django 5.1.5 on 2025-01-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_doctor_rating_doctor_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
