# Generated by Django 5.1.5 on 2025-01-21 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_remove_doctor_created_at_remove_doctor_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
