# Generated by Django 5.1.5 on 2025-01-21 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_specialization_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.CheckConstraint(condition=models.Q(('years_of_experience__gte', 0)), name='years_of_experience_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.CheckConstraint(condition=models.Q(('max_patients_per_day__gte', 1)), name='max_patients_per_day_positive'),
        ),
    ]
