# Generated by Django 5.1.5 on 2025-01-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctor_years_of_experience_non_negative_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='doctor',
            name='years_of_experience_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='doctor',
            name='max_patients_per_day_positive',
        ),
    ]
