# Generated by Django 5.1.5 on 2025-01-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_remove_doctor_years_of_experience_non_negative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
